export type contractDataType = {
  id?: string;
  centerName?: string[];
  bidNumber?: string;
  contractNumber?: string;
  contractType?: string;
  accountName?: string;
  contractName?: string;
  contractDate?: string;
  contractStartDate?: string;
  contractEndDate?: string;
  supplier?: string;
  baseBidPrice?: string;
  contractAmount?: string;
  contractMethod?: string;
  sn?: string;
  contractBond?: string;
  defectBond?: string;
  contractProposalNumber?: string;
  contractCategory?: string;
  manager?: string;
  etc?: string;
  viewStatus?: string;
  erpCode?: string;
  erpItem?: string;
  accountCategory?: string;
  modelName?: string;
  specifications?: string;
  manufacturer?: string;
  quantity?: string;
  unitPrice?: string;
  standard?: string;
  contractUnitPrice?: string;
  [key: string]: string | string[] | undefined;
};
