import type { Metadata } from "next";
import "./globals.css";
import { DarkModeProvider } from "@/context/DarkModeContext";

export const metadata: Metadata = {
  title: "구매팀",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <DarkModeProvider>
        <body>{children}</body>
      </DarkModeProvider>
    </html>
  );
}
