import type { Metadata } from "next";
import "./globals.css";
import { DarkModeProvider } from "@/context/DarkModeContext";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

// export const metadata: Metadata = {
//   title: "구매팀",
//   description: "Generated by create next app",
// };

export const metadata: Metadata = {
  title: {
    default: "구매팀",
    template: "%s - 구매팀",
  },
  description: "Generated by create next app",
  keywords: ["구매팀", "Next.js", "구매 관리"],
  openGraph: {
    title: "구매팀",
    description: "구매팀 전용 관리",
    url: "http://172.16.250.87:81/",
    siteName: "구매팀 App",
    locale: "ko_KR",
    type: "website",
  },
  icons: {
    icon: "/images/favicon.png",
    shortcut: "/images/favicon.png",
    apple: "/apple-touch-icon.png",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <DarkModeProvider>
        <body>
          {children}
          <ToastContainer />
        </body>
      </DarkModeProvider>
    </html>
  );
}
