import { bidDataType, bidListDataType } from "@/types/bidTypes";

export const bidData: bidDataType[] = [
  {
    id: "0",
    centerName: ["본원"],
    bidNumber: "구매(재)-2024-123-호",
    nuriMarket: "구매(재)-2024-123-호",
    contractType: "일반",
    bidMethod: "일반경쟁",
    accountName: "의료장비",
    announcementType: "본공고",
    bidName: "MRI",
    announcementDate: "2023-06-30T10:30:00.000",
    closingDate: "2023-06-30T10:30:00.000",
    bidDate: "2023-06-30T10:30:00.000",
    baseBidPrice: "100,000",
    winningBidPrice: "100,000",
    winner: "역산메디칼",
    bidResult: "유찰",
    bidBond: "O",
    bidProposalNumber: "한의112243",
    manager: "박정배",
    contractCategory: "ddd",
    etc: "",
    viewStatus: "저장",
  },
  {
    id: "1",
    centerName: ["본원", "제주"],
    bidNumber: "생성",
    nuriMarket: "",
    contractType: "일반",
    bidMethod: "일반경쟁",
    accountName: "의료장비",
    announcementType: "본공고",
    bidName: "MRI",
    announcementDate: "2023-01-01",
    closingDate: "2023-01-01",
    bidDate: "2023-01-01",
    baseBidPrice: "100,000",
    winningBidPrice: "100,000",
    winner: "역산메디칼",
    bidResult: "유찰",
    bidBond: "O",
    bidProposalNumber: "한의112243",
    manager: "박정배",
    etc: "",
    viewStatus: "저장",
  },
];

export const fields = [
  "id",
  "centerName",
  "bidNumber",
  "nuriMarket",
  "contractType",
  "bidMethod",
  "accountName",
  "announcementType",
  "bidName",
  "announcementDate",
  "closingDate",
  "bidDate",
  "baseBidPrice",
  "winningBidPrice",
  "winner",
  "bidResult",
  "bidBond",
  "bidProposalNumber",
  "manager",
  "contractCategory",
  "etc",
  "viewStatus",
];

export const fieldLabels: { [key in keyof bidDataType]: string } = {
  id: "ID",
  centerName: "센터",
  bidNumber: "입찰번호",
  nuriMarket: "누리장터",
  contractType: "계약종류",
  bidMethod: "낙찰방법",
  accountName: "계정명",
  announcementType: "공고구분",
  bidName: "입찰명",
  announcementDate: "공고일",
  closingDate: "마감일",
  bidDate: "응찰일",
  baseBidPrice: "낙찰기준가",
  winningBidPrice: "낙찰금액",
  winner: "낙찰자",
  bidResult: "입찰결과",
  bidBond: "입찰증권",
  bidProposalNumber: "입찰품의번호",
  manager: "담당자",
  contractCategory: "계약구분",
  etc: "기타",
  viewStatus: "열람",
};

export const bidListData: bidListDataType[] = [
  {
    id: "0",
    centerName: ["센터명", "부산"],
    erpCode: "ERP코드",
    erpItemName: "ERP품목명",
    accountType: "계정구분",
    modelName: "모델명",
    standard: "규격",
    manufacturer: "제조사",
    quantity: "수량",
    bidBaseUnitPrice: "2525000",
    bidBasePrice: "2323000",
  },
  {
    id: "2",
    centerName: ["센터명"],
    erpCode: "ERP코드",
    erpItemName: "ERP품목명",
    accountType: "계정구분",
    modelName: "모델명",
    standard: "규격",
    manufacturer: "제조사",
    quantity: "수량",
    bidBaseUnitPrice: "5588000",
    bidBasePrice: "5500000",
  },
];

export const bidListFields = [
  "id",
  "centerName",
  "erpCode",
  "erpItemName",
  "accountType",
  "modelName",
  "standard",
  "manufacturer",
  "quantity",
  "bidBaseUnitPrice",
  "bidBasePrice",
];

export const bidListFieldLabel: { [key in keyof bidListDataType]: string } = {
  id: "ID",
  centerName: "센터명",
  erpCode: "ERP코드",
  erpItemName: "ERP품목명",
  accountType: "계정구분",
  modelName: "모델명",
  standard: "규격",
  manufacturer: "제조사",
  quantity: "수량",
  bidBaseUnitPrice: "낙찰기준단가",
  bidBasePrice: "낙찰기준가격",
};
