import { contractDataType } from "@/types/contractTypes";

export const contractData: contractDataType[] = [
  {
    id: "0",
    centerName: ["본원", "제주"],
    bidNumber: "000011001",
    contractNumber: "000011001",
    contractType: "일반",
    accountName: "의료장비",
    contractName: "계약명",
    contractDate: "2023-01-01",
    contractStartDate: "2023-01-01",
    contractEndDate: "2023-01-01",
    supplier: "역산메디칼",
    baseBidPrice: "100,000",
    contractAmount: "100,000",
    contractMethod: "입찰",
    sn: "",
    contractBond: "O",
    defectBond: "X",
    contractProposalNumber: "한의112243",
    contractCategory: "최초계약",
    manager: "담당자",
    etc: "저장값",
    viewStatus: "저장",
  },
  {
    id: "1",
    centerName: ["본원", "제주"],
    bidNumber: "000011001",
    contractNumber: "000011001",
    contractType: "일반",
    accountName: "의료장비",
    contractName: "계약명",
    contractDate: "2023-01-01",
    contractStartDate: "2023-01-01",
    contractEndDate: "2023-01-01",
    supplier: "역산메디칼",
    baseBidPrice: "100,000",
    contractAmount: "100,000",
    contractMethod: "입찰",
    sn: "",
    contractBond: "O",
    defectBond: "X",
    contractProposalNumber: "한의112243",
    contractCategory: "최초계약",
    manager: "담당자",
    etc: "저장값",
    viewStatus: "저장",
  },
];

export const fields = [
  "id",
  "centerName",
  "bidNumber",
  "contractNumber",
  "contractType",
  "accountName",
  "contractName",
  "contractDate",
  "contractStartDate",
  "contractEndDate",
  "supplier",
  "baseBidPrice",
  "contractAmount",
  "contractMethod",
  "sn",
  "contractBond",
  "defectBond",
  "contractProposalNumber",
  "contractCategory",
  "manager",
  "etc",
  "viewStatus",
];

export const fieldLabels: { [key in keyof contractDataType]: string } = {
  id: "id",
  centerName: "센터",
  bidNumber: "입찰번호",
  contractNumber: "계약번호",
  contractType: "계약종류",
  accountName: "계정명",
  contractName: "계약명",
  contractDate: "계약일자",
  contractStartDate: "계약시작일",
  contractEndDate: "계약완료일",
  supplier: "공급사",
  baseBidPrice: "낙찰기준가",
  contractAmount: "계약금액",
  contractMethod: "계약방법",
  sn: "SN",
  contractBond: "계약증권",
  defectBond: "하자증권",
  contractProposalNumber: "계약품의번호",
  contractCategory: "계약구분",
  manager: "담당자",
  etc: "기타",
  viewStatus: "열람",
};

//

export const contractListData: contractDataType[] = [
  {
    id: "0",
    centerName: ["본원", "제주"],
    erpCode: "ERP코드",
    erpItem: "ERP품목",
    bidNumber: "입찰번호",
    contractNumber: "계약번호",
    contractType: "계약종류",
    accountCategory: "계정구분",
    modelName: "모델명",
    standard: "규격",
    manufacturer: "제조사",
    supplier: "공급사",
    quantity: "수량",
    baseBidPrice: "낙찰기준가",
    contractUnitPrice: "계약단가",
    contractAmount: "계약금액",
  },
  {
    id: "1",
    centerName: ["본원", "제주"],
    erpCode: "ERP코드",
    erpItem: "ERP품목",
    bidNumber: "입찰번호",
    contractNumber: "계약번호",
    contractType: "계약종류",
    accountCategory: "계정구분",
    modelName: "모델명",
    standard: "규격",
    manufacturer: "제조사",
    supplier: "공급사",
    quantity: "수량",
    baseBidPrice: "낙찰기준가",
    contractUnitPrice: "계약단가",
    contractAmount: "계약금액",
  },
];

export const contractListFields = [
  "centerName",
  "erpCode",
  "erpItem",
  "accountCategory",
  "modelName",
  "specifications",
  "manufacturer",
  "quantity",
  "unitPrice",
];

export const contractListLabels: { [key in keyof contractDataType]: string } = {
  centerName: "센터",
  erpCode: "ERP코드",
  erpItem: "ERP품목",
  bidNumber: "입찰번호",
  contractNumber: "계약번호",
  contractType: "계약종류",
  accountCategory: "계정구분",
  modelName: "모델명",
  standard: "규격",
  manufacturer: "제조사",
  supplier: "공급사",
  quantity: "수량",
  baseBidPrice: "낙찰기준가",
  contractUnitPrice: "계약단가",
  contractAmount: "계약금액",
};
