export const data = [
  {
    id: "0",
    data1: "The Sliding Mr. Bones",
    data2: "Malcolm Lockyer",
    data3: "1961",
  },
  { id: "1", data1: "Witchy Woman", data2: "The Eagles", data3: "1972" },
  {
    id: "2",
    data1: "Shining Star",
    data2: "Earth, Wind, and Fire",
    data3: "1975",
  },
  {
    id: "3",
    data1: "The Sliding Mr. Bones",
    data2: "Malcolm Lockyer",
    data3: "1961",
  },
  { id: "4", data1: "Witchy Woman", data2: "The Eagles", data3: "1972" },
  {
    id: "5",
    data1: "Shining Star",
    data2: "Earth, Wind, and Fire",
    data3: "1975",
  },
  {
    id: "6",
    data1: "The Sliding Mr. Bones",
    data2: "Malcolm Lockyer",
    data3: "1961",
  },
  { id: "7", data1: "Witchy Woman", data2: "The Eagles", data3: "1972" },
  {
    id: "8",
    data1: "Shining Star",
    data2: "Earth, Wind, and Fire",
    data3: "1975",
  },
  {
    id: "9",
    data1: "The Sliding Mr. Bones",
    data2: "Malcolm Lockyer",
    data3: "1961",
  },
  { id: "10", data1: "Witchy Woman", data2: "The Eagles", data3: "1972" },
  {
    id: "11",
    data1: "Shining Star",
    data2: "Earth, Wind, and Fire",
    data3: "1975",
  },
  {
    id: "12",
    data1: "The Sliding Mr. Bones",
    data2: "Malcolm Lockyer",
    data3: "1961",
  },
  { id: "13", data1: "Witchy Woman", data2: "The Eagles", data3: "1972" },
  {
    id: "14",
    data1: "Shining Star",
    data2: "Earth, Wind, and Fire",
    data3: "1975",
  },
  {
    id: "15",
    data1: "The Sliding Mr. Bones",
    data2: "Malcolm Lockyer",
    data3: "1961",
  },
  { id: "16", data1: "Witchy Woman", data2: "The Eagles", data3: "1972" },
  {
    id: "17",
    data1: "Shining Star",
    data2: "Earth, Wind, and Fire",
    data3: "1975",
  },
  {
    id: "18",
    data1: "The Sliding Mr. Bones",
    data2: "Malcolm Lockyer",
    data3: "1961",
  },
  { id: "19", data1: "Witchy Woman", data2: "The Eagles", data3: "1972" },
  {
    id: "20",
    data1: "Shining Star",
    data2: "Earth, Wind, and Fire",
    data3: "1975",
  },
  {
    id: "21",
    data1: "The Sliding Mr. Bones",
    data2: "Malcolm Lockyer",
    data3: "1961",
  },
  { id: "22", data1: "Witchy Woman", data2: "The Eagles", data3: "1972" },
  {
    id: "23",
    data1: "Shining Star",
    data2: "Earth, Wind, and Fire",
    data3: "1975",
  },
  {
    id: "24",
    data1: "The Sliding Mr. Bones",
    data2: "Malcolm Lockyer",
    data3: "1961",
  },
  { id: "25", data1: "Witchy Woman", data2: "The Eagles", data3: "1972" },
  {
    id: "26",
    data1: "Shining Star",
    data2: "Earth, Wind, and Fire",
    data3: "1975",
  },
  {
    id: "27",
    data1: "The Sliding Mr. Bones",
    data2: "Malcolm Lockyer",
    data3: "1961",
  },
  { id: "28", data1: "Witchy Woman", data2: "The Eagles", data3: "1972" },
  {
    id: "29",
    data1: "Shining Star",
    data2: "Earth, Wind, and Fire",
    data3: "1975",
  },
  {
    id: "30",
    data1: "The Sliding Mr. Bones",
    data2: "Malcolm Lockyer",
    data3: "1961",
  },
  { id: "31", data1: "Witchy Woman", data2: "The Eagles", data3: "1972" },
  {
    id: "32",
    data1: "Shining Star",
    data2: "Earth, Wind, and Fire",
    data3: "1975",
  },
  {
    id: "33",
    data1: "The Sliding Mr. Bones",
    data2: "Malcolm Lockyer",
    data3: "1961",
  },
  { id: "34", data1: "Witchy Woman", data2: "The Eagles", data3: "1972" },
  {
    id: "35",
    data1: "Shining Star",
    data2: "Earth, Wind, and Fire",
    data3: "1975",
  },
];

export const columns = ["data1", "data2", "data3"];
