export const tenderMapping = {
  centerName: "센터",
  bidNumber: "입찰번호",
  nuriMarket: "누리장터",
  contractType: "계약종류",
  bidMethod: "낙찰방법",
  accountName: "계정명",
  announcementType: "공고구분",
  bidName: "입찰명",
  announcementDate: "공고일",
  closingDate: "마감일",
  bidDate: "응찰일",
  baseBidPrice: "낙찰기준가",
  winningBidPrice: "낙찰금액",
  winner: "낙찰자",
  bidResult: "입찰결과",
  bidBond: "입찰증권",
  bidProposalNumber: "입찰품의번호",
  manager: "담당자",
  contractCategory: "계약구분",
  etc: "기타",
  viewStatus: "열람",
};

export const tenderErpMapping = {
  centerName: "센터명",
  erpCode: "ERP코드",
  erpItemNm: "ERP품목명",
  accountType: "계정구분",
  modelName: "모델명",
  standard: "규격",
  manufacturer: "제조사",
  quantity: "수량",
  bidBaseUnitPrice: "낙찰기준단가",
  baseBidPrice: "낙찰기준가",
};

export const contractMapping = {
  centerName: "센터",
  bidNumber: "입찰번호",
  erpItemNm: "ERP품목명",
  contractNumber: "계약번호",
  contractType: "계약종류",
  accountName: "계정명",
  contractName: "계약명",
  contractDate: "계약일자",
  contractStartDate: "계약시작일",
  contractEndDate: "계약완료일",
  supplier: "공급사",
  baseBidPrice: "낙찰기준가",
  contractAmount: "계약금액",
  contractMethod: "계약방법",
  sn: "SN",
  contractBond: "계약증권",
  defectBond: "하자증권",
  contractProposalNumber: "계약품의번호",
  contractCategory: "계약구분",
  manager: "담당자",
  etc: "기타",
  viewStatus: "열람",
};

export const contractErpMapping = {
  centerName: "센터명",
  erpCode: "ERP코드",
  erpItemNm: "ERP품목명",
  bidNumber: "입찰번호",
  contractNumber: "계약번호",
  contractType: "계약종류",
  accountCategory: "계정구분",
  modelName: "모델명",
  standard: "규격",
  manufacturer: "제조사",
  supplier: "공급사",
  quantity: "수량",
  baseBidPrice: "낙찰기준가",
  contractUnitPrice: "계약단가",
  contractAmount: "계약금액",
  baseBidUnitPrice: "낙찰기준단가",
};
